number1 = input ("Enter first number:")
number2 = input ("Enter second number:")
result1 = int(number1) + int(number2) 
result2 = int(number1) - int(number2)
result3 = int(number1) * int(number2)
result4 = int(number1) / int(number2)
result5 = int(number1) % int(number2)
result6 = int(number1) ** int(number2)

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
